[context.production]
  command = "npm run generate:prod"

[context.deploy-preview]
  command = "npm run generate:preview"

[context.branch-deploy]
  command = "NUXT_BUILD_IGNORE_WARNINGS=true npm run generate:dev"

[build]
  node_version = "18.17.1"