[context.production]
  command = "npm run generate:prod"

[context.deploy-preview]
  command = "npm run generate:preview"

[context.branch-deploy]
  command = "npm run generate:dev"

[build]
  node_version = "18.17.1"

[[redirects]]
  from = "/sql_everyone"
  to = "https://sql-everyone.com/"
  status = 301